### ISSUE TITLE
Can't execute

### ISSUE THREAD

**Issue by rummanz** [Jvanrhijn/polybar-spotify#13]
Traceback (most recent call last):
  File "/home/username/.config/polybar/scripts/spotify_status.py", line 70, in <module>
    session_bus = dbus.SessionBus()
AttributeError: module 'dbus' has no attribute 'SessionBus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/username/.config/polybar/scripts/spotify_status.py", line 119, in <module>
    if isinstance(e, dbus.exceptions.DBusException):
AttributeError: module 'dbus' has no attribute 'exceptions'

**Comment by saurabh000345** [comment]
Install `python-dbus`
It's a dependency. The script will execute after that

**Comment by rummanz** [comment]
Thanks, it works!
